version: "3.0"

services:
  poretreat-site:
    image: jekyll/jekyll:3.8
    container_name: poretreat-site
    volumes:
      - .:/srv/jekyll
    ports:
      - 8080:4000
    entrypoint: jekyll serve #-H localhost
